In [3]:
import numpy as np


fleet_data = np.array([
    [120, 40, 25, 2.5, 10],
    [85, 60, 30, 5.0, 5],
    [100, 50, 35, 4.5, 7],
    [120, 40, 25, 2.5, 9],
    [150, 50, 30, 3.0, 10],
], dtype=np.float32)

Calculate and print the total number of spaceships.

In [4]:
ship_lengths = fleet_lenght = fleet_data.shape[0]
f"Number of ships in the fleet: {fleet_lenght}"

'Number of ships in the fleet: 5'

Calculate and print the average spaceship size (volume).

In [5]:
ship_lengths = fleet_data[:, 0]
ship_widths = fleet_data[:, 1]
ship_heigths = fleet_data[:, 2]

print(f"Lengths: {ship_lengths}")
print(f"Widths: {ship_widths}")
print(f"Heights: {ship_heigths}")

Lengths: [120.  85. 100. 120. 150.]
Widths: [40. 60. 50. 40. 50.]
Heights: [25. 30. 35. 25. 30.]


In [6]:
ships_volumes = ship_lengths*ship_widths*ship_heigths
ships_volumes

array([120000., 153000., 175000., 120000., 225000.], dtype=float32)

In [7]:
ships_mean_volume = ships_volumes.mean()
f"Mean volume of the ships: {ships_mean_volume} m3"

'Mean volume of the ships: 158600.0 m3'

Identify and print the speed of the fastest spaceship.

In [8]:
ship_speed = fleet_data[:, 3]

print(f"Speed: {ship_speed}")
max_speed = ship_speed.max()
ship_max_speed = np.argmax(ship_speed)
f"The fastest ship ({ship_max_speed}) travels at {max_speed} km/s"

Speed: [2.5 5.  4.5 2.5 3. ]


'The fastest ship (1) travels at 5.0 km/s'

In [9]:
np.argmax

<function argmax at 0x7fb0305e8530>

Determine and print the number of spaceships with the maximum weapon power.


In [21]:
ship_weapon_power = fleet_data[:, 4]
ships_with_max_power_mask = ship_weapon_power == 10
n_ships_max_power = ships_with_max_power_mask.sum()

f"The number of ships with max power is {n_ships_max_power}"

'The number of ships with max power is 2'

Find and print the mean speed of spaceships with the maximum weapon power.

In [25]:
ship_speed, ships_with_max_power_mask

(array([2.5, 5. , 4.5, 2.5, 3. ], dtype=float32),
 array([ True, False, False, False,  True]))

In [27]:
ship_speed[ships_with_max_power_mask].mean()

2.75